### ISSUE TITLE
cannot change end date for range

### ISSUE THREAD

**Issue by phelbas** [TIOvOIT/praecox-datepicker#3]
perhaps after both dates are selected a new click should erase both and interpret new click as start date?

**Comment by TIOvOIT** [comment]
You can reset the end date to the start date by double clicking.

**Comment by TIOvOIT** [comment]
This feature support has been added in version 1.0.0

**Comment by TIOvOIT** [comment]
You can set the `reSelected` prop to true to activate the feature
