### ISSUE TITLE
Highlight pre-selected dates

### ISSUE THREAD

**Issue by patagoniapy** [TIOvOIT/praecox-datepicker#6]
Is there a way to style dates that have been previously selected? For example, as a user selects dates, possibly store those in an array and then add some type of styling to the calendar (change of color, dot on the date, etc.) that indicates the user has already interacted with that date?

**Comment by TIOvOIT** [comment]
Are you using the latest version?

**Comment by patagoniapy** [comment]
No but I can be. Is there a prop for this? The documentation is a little unclear to me.

**Comment by TIOvOIT** [comment]
> No but I can be. Is there a prop for this? The documentation is a little unclear to me.

Versions prior to 1.0.0 have no props for two-way binding of the selected date.

**Comment by patagoniapy** [comment]
Is there a way to demonstrate this in the REPL? I don't see how the two-way binding works, or a way to add styling to dates? Also, it appears the dates aren't calculating properly as Monday/Sunday of the weeks are showing the same date (i.e. each date is getting shown twice)

Here is a REPL link: https://svelte.dev/repl/73e7c57185e7404e96a90cfc1555c8ed?version=3.31.0

**Comment by TIOvOIT** [comment]
> 有没有办法在REPL中证明这一点？我看不到双向绑定是如何工作的，或者没有为日期添加样式的方法？另外，似乎日期计算不正确，因为每周的星期一/星期日显示相同的日期（即每个日期显示两次）
> 
> 这是一个REPL链接：[https](https://svelte.dev/repl/73e7c57185e7404e96a90cfc1555c8ed?version=3.31.0) ://svelte.dev/repl/73e7c57185e7404e96a90cfc1555c8ed [?](https://svelte.dev/repl/73e7c57185e7404e96a90cfc1555c8ed?version=3.31.0) version [=](https://svelte.dev/repl/73e7c57185e7404e96a90cfc1555c8ed?version=3.31.0) 3.31.0[](https://svelte.dev/repl/73e7c57185e7404e96a90cfc1555c8ed?version=3.31.0)
[Preview REPL](https://svelte.dev/repl/f153bee994974251b59041832a099427?version=3.29.0)
The `selected `prop is used to bind the selected date.
The `viewDate` prop is used to control the date displayed in the current view.
