### ISSUE TITLE
April has two 4ths 

### ISSUE THREAD

**Issue by phelbas** [TIOvOIT/praecox-datepicker#7]
From your demo

<img width="345" alt="Screen Shot 2020-12-15 at 6 32 39 pm" src="https://user-images.githubusercontent.com/67846089/102184692-f7d03000-3f03-11eb-8ebe-e420b2f5c391.png">

**Comment by TIOvOIT** [comment]
Hi, it can be displayed normally on my computer.
Operating System: Windows 10 pro 1909
Browser: Chrome 87.0.4280.88

Can you disclose your use environment?

**Comment by phelbas** [comment]
safari on a mac in australia timezone
at a guess it is a timezone issue from daylight saving which is 4th april, you add 24 hours of seconds but of course one day a year has more than 24 hours...

**Comment by TIOvOIT** [comment]
> safari on a mac in australia timezone
> at a guess it is a timezone issue from daylight saving which is 4th april, you add 24 hours of seconds but of course one day a year has more than 24 hours...

Then I may be sorry, there is no plan to support daylight saving time. 
Supporting daylight saving time may be far away.

**Comment by TIOvOIT** [comment]
Of course, you are also welcome to contribute to this project to support daylight saving time

**Comment by phelbas** [comment]
Most countries use daylight savings time, so it will display double dates for any user whose browser is in a timezone that has daylight savings time (jump forward one hour) once a year.

I think the code to build dates displayed should use this type thing instead of adding/subtracting milliseconds:
https://stackoverflow.com/questions/563406/add-days-to-javascript-date

**Comment by TIOvOIT** [comment]
> Most countries use daylight savings time, so it will display double dates for any user whose browser is in a timezone that has daylight savings time (jump forward one hour) once a year.
> 
> I think the code to build dates displayed should use this type thing instead of adding/subtracting milliseconds:
> https://stackoverflow.com/questions/563406/add-days-to-javascript-date

Thanks for your suggestion, I will consider it in the next update.

**Comment by asahelk** [comment]
![image](https://user-images.githubusercontent.com/12284349/115832731-d95dd200-a3d8-11eb-970e-8eb7e4a67083.png)
I'm having the same issue with three 9ths in October
